name: ${name}
description: ${description}
version: ${version}
authors: [${author}]
main: ${mainClass}
website: ${parent.url}
depend: [LuckPerms]

api-version: 1.13

commands:
  lpgroupsync:
    aliases: [lpsync]
    usage: /<command>
    permission: lpgroupsync.command